"""empty message

Revision ID: 261a5a3f811d
Revises: fa293fa698cb
Create Date: 2022-01-24 15:21:49.158962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261a5a3f811d' # pragma: allowlist secret
down_revision = 'fa293fa698cb' # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_resource', sa.Column('type', sa.Enum('UNKNOWN', 'VIRTUAL_MACHINE', 'CONTAINER', 'NETWORK', 'REPOSITORY', 'PIPELINE', 'OBJECT_STORAGE', 'DATABASE', 'FUNCTION', 'STORAGE', name='monitoredresourcetype'), nullable=False))
    op.add_column('technical_control', sa.Column('ttl', sa.Integer(), nullable=True))
    op.add_column('technical_control', sa.Column('is_blocking', sa.Boolean(), nullable=False))
    op.add_column('technical_control', sa.Column('can_delete_resources', sa.Boolean(), nullable=False))
    op.add_column('technical_control', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'technical_control', 'technical_control', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'technical_control', type_='foreignkey')
    op.drop_column('technical_control', 'parent_id')
    op.drop_column('technical_control', 'can_delete_resources')
    op.drop_column('technical_control', 'is_blocking')
    op.drop_column('technical_control', 'ttl')
    op.drop_column('monitored_resource', 'type')
    # ### end Alembic commands ###
