"""empty message

Revision ID: 76d59e0556b7
Revises: 8fc3cdedea53
Create Date: 2021-12-09 13:45:20.193756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "76d59e0556b7"
down_revision = "8fc3cdedea53"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "system", "stage", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    # ### end Alembic commands ###
    op.execute("ALTER TYPE monitoredresourcestate ADD VALUE 'MONITORING'")
    op.execute("ALTER TYPE monitoredresourcestate ADD VALUE 'CANCELLED'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "system", "stage", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###
