"""empty message

Revision ID: 784fd28a0a2b
Revises: ce6c2ec1b480
Create Date: 2021-11-08 15:29:43.049138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784fd28a0a2b'
down_revision = 'ce6c2ec1b480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_application_type_name', 'application_type', ['name'])
    op.create_unique_constraint('uq_system', 'system', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_system', 'system', type_='unique')
    op.drop_constraint('uq_application_type_name', 'application_type', type_='unique')
    # ### end Alembic commands ###
