"""empty message

Revision ID: 8fc3cdedea53
Revises: cfe862b70929
Create Date: 2021-12-06 20:14:43.303619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8fc3cdedea53"
down_revision = "cfe862b70929"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name="monitored_resource",
        column_name="state",
        new_column_name="monitoring_state",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name="monitored_resource",
        column_name="monitoring_state",
        new_column_name="state",
    )
    # ### end Alembic commands ###
