"""empty message

Revision ID: ce6c2ec1b480
Revises:
Create Date: 2021-11-03 10:27:45.327574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6c2ec1b480'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation', name='uq_environment')
    )
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('application_type_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_type_id'], ['application_type.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('reference', sa.String(length=500), nullable=False),
    sa.Column('control_type_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='technicalcontrolseverity'), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'reference', name='uq_technical_control')
    )
    op.create_table('application_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=500), nullable=False),
    sa.Column('reference', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'type', name='uq_application_type'),
    sa.UniqueConstraint('type', 'reference', name='uq_application_reference')
    )
    op.create_table('application_technical_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('technical_control_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['technical_control_id'], ['technical_control.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'technical_control_id', name='uq_application_technical_control')
    )
    op.create_table('exclusion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_technical_control_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('mitigation', sa.String(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('is_limited_exclusion', sa.Boolean(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['application_technical_control_id'], ['application_technical_control.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitored_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=500), nullable=False),
    sa.Column('state', sa.Enum('FLAGGED', 'SUPPRESSED', 'FIXED_AUTO', 'FIXED_OTHER', name='monitoredresourcestate'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('application_technical_control_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_technical_control_id'], ['application_technical_control.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_technical_control_id', 'reference', name='uq_monitored_resource')
    )
    op.create_table('exclusion_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exclusion_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('NONE', 'PENDING', 'ACTIVE', name='exclusionstate'), nullable=False),
    sa.ForeignKeyConstraint(['exclusion_id'], ['exclusion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exclusion_resource')
    op.drop_table('monitored_resource')
    op.drop_table('exclusion')
    op.drop_table('application_technical_control')
    op.drop_table('application_reference')
    op.drop_table('technical_control')
    op.drop_table('application')
    op.drop_table('system')
    op.drop_table('environment')
    op.drop_table('application_type')
    # ### end Alembic commands ###
