repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-ast
  - id: detect-aws-credentials
  - id: detect-private-key
  - id: mixed-line-ending


- repo: git@github.com:Yelp/detect-secrets
  rev: v1.1.0
  hooks:
  -   id: detect-secrets
      args: ['--baseline', '.secrets.baseline']
      exclude: package.lock.json
